name: Full CI/CD Pipeline

permissions: #permission for reports to be uploaded to GitHub Security tab.
  contents: read
  security-events: write

on:
  push:
    branches: [main]
    paths:
      - '.github/**'
      - 'backend/**'
  pull_request:
    paths:
      - '.github/**'
      - 'backend/**'

env:
  IMAGE_NAME: koyex1/backend
  NODE_VERSION: 20.20.0

jobs:

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: checkout code(lint)
        uses: actions/checkout@v4

      - name: setup node(lint)
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: install dependencies(lint)
        run: npm ci
        #working-directory: ./backend (but instead of handling at the step level, we can handle it at the workflow level by setting defaults for the entire workflow)

      - name: run linter
        run: npm run lint
        #working-directory: ./backend

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    needs: lint
    steps:
      - name: Checkout code(test)
        uses: actions/checkout@v4

      - name: Setup Node.js(test)
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies(test)
        run: npm ci

      - name: Run tests with coverage and JUnit reporting
        run: npm test -- --coverage --ci --reporters=default --reporters=jest-junit

      - name: Upload JUnit Report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: ./backend/junit.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./backend/coverage/

  sonar:
    if: false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    needs: test
    steps:
      - name: Checkout code(sonar)
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=sonarqubepjt
            -Dsonar.sources=.
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*.test.js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  dependency-scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code(dependency scan)
        uses: actions/checkout@v4

      - name: Trivy FS Scan (JSON)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          format: json
          output: trivy-fs-report.json
          exit-code: 0
          severity: CRITICAL,HIGH

      - name: Upload FS Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-report
          path: .backend/trivy-fs-report.json

      - name: Trivy FS Scan (SARIF)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          format: sarif
          output: trivy-results.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

  build-and-image-scan:
    needs: [dependency-scan]
    uses: ./.github/workflows/reusable-build.yml
    with:
      image_name: $IMAGE_NAME
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    needs: build-and-image-scan
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull $IMAGE_NAME:latest
            docker stop app || true
            docker rm app || true
            docker run -d \
              --name app \
              -p 4000:4000 \
              --restart unless-stopped \
              $IMAGE_NAME:latest